### ISSUE TITLE
Test::Unit::AutoRunner (NameError)

### ISSUE THREAD

**Issue by mitsuru793** [guard/guard-test#60]
Hi, I'm mitsuru793. I have made my gem.
I use guard-test latest 2.0.6 and run `bundle exec guard`, I get an error `Test::Unit::AutoRunner (NameError)`.

However, at v2.0.5 I don't get this error, so I have used 2.0.5.

```
❯ bundle exec guard
19:41:54 - INFO - Guard::Test 2.0.6 is running, with Test::Unit 3.1.8!
19:41:54 - INFO - Running all tests
/Users/mitsuru/code/script/dig_yaml_front_matter/vendor/ruby/2.3.0/gems/guard-test-2.0.6/lib/guard/test/guard_test_runner.rb:36:in `<top (required)>': uninitialized constant Test::Unit::AutoRunner (NameError)
        from -e:1:in `require'
19:41:55 - INFO - Guard is now watching at '/Users/mitsuru/code/script/dig_yaml_front_matter'
```

I install gem into `./vendor`. and my ruby version is `ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]`
My OS is OS X El Capitan 10.11.1 .

```
❯ bundle list
Gems included by the bundle:
  * awesome_print (1.6.1)
  * bundler (1.11.2)
  * coderay (1.1.1)
  * dig_yaml_front_matter (0.1.0)
  * ffi (1.9.10)
  * formatador (0.2.5)
  * guard (2.13.0)
  * guard-compat (1.2.1)
  * guard-test (2.0.6)
  * listen (3.0.6)
  * lumberjack (1.0.10)
  * method_source (0.8.2)
  * nenv (0.3.0)
  * notiffany (0.0.8)
  * power_assert (0.2.7)
  * pry (0.10.3)
  * rake (10.5.0)
  * rb-fsevent (0.9.7)
  * rb-inotify (0.9.7)
  * shellany (0.0.1)
  * slop (3.6.0)
  * terminal-notifier (1.6.3)
  * terminal-notifier-guard (1.7.0)
  * test-unit (3.1.8)
  * thor (0.19.1)
```

My GuardFile is here.
```
guard :test, cmd: "bundle exec test" do
  # Test files
  watch(%r{^test/.+_test\.rb$})
  watch(%r{^lib/(.+)\.rb$}) { |m| "test/lib/#{m[1]}_test.rb" }
  watch('test/test_helper.rb') { "test" }
end
```

**Comment by rymai** [comment]
Hi @mitsuru793, the `test-unit` dependency was updated (in 20836b714c66fee61ce61a4028d2532c967c2f8d) to `~> 3.0` in `guard-test` `v2.0.6`, that probably explains why it worked with `guard-test` `v2.0.5` but not with `guard-test` `v2.0.6`.

That being said, adding `require 'test/unit/autorunner'` at the top of `lib/guard/test/guard_test_runner.rb` might fix it... I'll open a PR and ping you to see if that fixes it.

**Comment by mitsuru793** [comment]
@rymai Thank you very much! Your fix helped me. I have no problem and your code worked well.
